### PR TITLE
fix: drop deps when building hist-base

### PR DESCRIPTION
**Pull request by agoose77**

### CODE REVIEW

**Comment by agoose77** [comment]
@henryiii I'd benefit from your expertise here.

The hist-base pip dependencies are being included in the built package, which we _don't_ want.

What I'm confused about is why this doesn't seem to be a problem for non-meta packages (I see many packages not using `--no-deps`). I think therefore I'd assumed that conda includes the relevant metadata such that pip identifies that the dependencies are already in the environment. Thus, my outstanding questions are:
1. Is `--no-deps` always required? / Does conda provide sufficient metadata for `--no-deps` to not always be needed?
2. Why is this only something I observe for meta-package recipes?

In any case, I built this locally and confirmed that it fixes the problem.

**Comment by agoose77** [comment]
@conda-forge-admin please, rerender

**Comment by agoose77** [comment]
@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
Matplotlib is using this, so let’s do it. I would have sworn PIP_NO_DEPS was set by conda-build though.

**Comment by agoose77** [comment]
> I would have sworn PIP_NO_DEPS was set by conda-build though.

That would sound like a sensible default. I'll do some digging.

**Pull request merged**
